apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whatomate.fullname" . }}-config
  labels:
    {{- include "whatomate.labels" . | nindent 4 }}
data:
  config.toml: |
{{ tpl .Values.whatomateConfig . | indent 4 }}
